//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/reader/PointOfInterest.java
//

#include "J2ObjC_source.h"
#include "java/util/List.h"
#include "org/mapsforge/core/model/LatLong.h"
#include "org/mapsforge/map/reader/PointOfInterest.h"

@implementation OrgMapsforgeMapReaderPointOfInterest

- (instancetype)initWithByte:(jbyte)layer
            withJavaUtilList:(id<JavaUtilList>)tags
withOrgMapsforgeCoreModelLatLong:(OrgMapsforgeCoreModelLatLong *)position {
  OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(self, layer, tags, position);
  return self;
}

- (jboolean)isEqual:(id)obj {
  if (self == obj) {
    return true;
  }
  else if (!([obj isKindOfClass:[OrgMapsforgeMapReaderPointOfInterest class]])) {
    return false;
  }
  OrgMapsforgeMapReaderPointOfInterest *other = (OrgMapsforgeMapReaderPointOfInterest *) cast_chk(obj, [OrgMapsforgeMapReaderPointOfInterest class]);
  if (self->layer_ != ((OrgMapsforgeMapReaderPointOfInterest *) nil_chk(other))->layer_) {
    return false;
  }
  else if (![((id<JavaUtilList>) nil_chk(self->tags_)) isEqual:other->tags_]) {
    return false;
  }
  else if (![((OrgMapsforgeCoreModelLatLong *) nil_chk(self->position_)) isEqual:other->position_]) {
    return false;
  }
  return true;
}

- (NSUInteger)hash {
  jint prime = 31;
  jint result = 1;
  result = prime * result + layer_;
  result = prime * result + ((jint) [((id<JavaUtilList>) nil_chk(tags_)) hash]);
  result = prime * result + ((jint) [((OrgMapsforgeCoreModelLatLong *) nil_chk(position_)) hash]);
  return result;
}

- (void)dealloc {
  RELEASE_(position_);
  RELEASE_(tags_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, 1, -1, -1 },
    { NULL, "Z", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 4, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithByte:withJavaUtilList:withOrgMapsforgeCoreModelLatLong:);
  methods[1].selector = @selector(isEqual:);
  methods[2].selector = @selector(hash);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "layer_", "B", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "position_", "LOrgMapsforgeCoreModelLatLong;", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "tags_", "LJavaUtilList;", .constantValue.asLong = 0, 0x11, -1, -1, 5, -1 },
  };
  static const void *ptrTable[] = { "BLJavaUtilList;LOrgMapsforgeCoreModelLatLong;", "(BLjava/util/List<Lorg/mapsforge/core/model/Tag;>;Lorg/mapsforge/core/model/LatLong;)V", "equals", "LNSObject;", "hashCode", "Ljava/util/List<Lorg/mapsforge/core/model/Tag;>;" };
  static const J2ObjcClassInfo _OrgMapsforgeMapReaderPointOfInterest = { "PointOfInterest", "org.mapsforge.map.reader", ptrTable, methods, fields, 7, 0x1, 3, 3, -1, -1, -1, -1, -1 };
  return &_OrgMapsforgeMapReaderPointOfInterest;
}

@end

void OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(OrgMapsforgeMapReaderPointOfInterest *self, jbyte layer, id<JavaUtilList> tags, OrgMapsforgeCoreModelLatLong *position) {
  NSObject_init(self);
  self->layer_ = layer;
  JreStrongAssign(&self->tags_, tags);
  JreStrongAssign(&self->position_, position);
}

OrgMapsforgeMapReaderPointOfInterest *new_OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(jbyte layer, id<JavaUtilList> tags, OrgMapsforgeCoreModelLatLong *position) {
  J2OBJC_NEW_IMPL(OrgMapsforgeMapReaderPointOfInterest, initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_, layer, tags, position)
}

OrgMapsforgeMapReaderPointOfInterest *create_OrgMapsforgeMapReaderPointOfInterest_initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_(jbyte layer, id<JavaUtilList> tags, OrgMapsforgeCoreModelLatLong *position) {
  J2OBJC_CREATE_IMPL(OrgMapsforgeMapReaderPointOfInterest, initWithByte_withJavaUtilList_withOrgMapsforgeCoreModelLatLong_, layer, tags, position)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMapsforgeMapReaderPointOfInterest)
