//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/CorruptedInputStreamException.java
//

#include "J2ObjC_source.h"
#include "java/lang/RuntimeException.h"
#include "org/mapsforge/core/graphics/CorruptedInputStreamException.h"

inline jlong OrgMapsforgeCoreGraphicsCorruptedInputStreamException_get_serialVersionUID();
#define OrgMapsforgeCoreGraphicsCorruptedInputStreamException_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgMapsforgeCoreGraphicsCorruptedInputStreamException, serialVersionUID, jlong)

@implementation OrgMapsforgeCoreGraphicsCorruptedInputStreamException

- (instancetype)initWithNSString:(NSString *)detailMessage
                 withNSException:(NSException *)throwable {
  OrgMapsforgeCoreGraphicsCorruptedInputStreamException_initWithNSString_withNSException_(self, detailMessage, throwable);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgMapsforgeCoreGraphicsCorruptedInputStreamException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LNSException;" };
  static const J2ObjcClassInfo _OrgMapsforgeCoreGraphicsCorruptedInputStreamException = { "CorruptedInputStreamException", "org.mapsforge.core.graphics", ptrTable, methods, fields, 7, 0x1, 1, 1, -1, -1, -1, -1, -1 };
  return &_OrgMapsforgeCoreGraphicsCorruptedInputStreamException;
}

@end

void OrgMapsforgeCoreGraphicsCorruptedInputStreamException_initWithNSString_withNSException_(OrgMapsforgeCoreGraphicsCorruptedInputStreamException *self, NSString *detailMessage, NSException *throwable) {
  JavaLangRuntimeException_initWithNSString_withNSException_(self, detailMessage, throwable);
}

OrgMapsforgeCoreGraphicsCorruptedInputStreamException *new_OrgMapsforgeCoreGraphicsCorruptedInputStreamException_initWithNSString_withNSException_(NSString *detailMessage, NSException *throwable) {
  J2OBJC_NEW_IMPL(OrgMapsforgeCoreGraphicsCorruptedInputStreamException, initWithNSString_withNSException_, detailMessage, throwable)
}

OrgMapsforgeCoreGraphicsCorruptedInputStreamException *create_OrgMapsforgeCoreGraphicsCorruptedInputStreamException_initWithNSString_withNSException_(NSString *detailMessage, NSException *throwable) {
  J2OBJC_CREATE_IMPL(OrgMapsforgeCoreGraphicsCorruptedInputStreamException, initWithNSString_withNSException_, detailMessage, throwable)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMapsforgeCoreGraphicsCorruptedInputStreamException)
