//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/GraphicUtils.java
//

#include "J2ObjC_source.h"
#include "org/mapsforge/core/graphics/GraphicUtils.h"

@interface OrgMapsforgeCoreGraphicsGraphicUtils ()

- (instancetype)init;

@end

__attribute__((unused)) static void OrgMapsforgeCoreGraphicsGraphicUtils_init(OrgMapsforgeCoreGraphicsGraphicUtils *self);

__attribute__((unused)) static OrgMapsforgeCoreGraphicsGraphicUtils *new_OrgMapsforgeCoreGraphicsGraphicUtils_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgMapsforgeCoreGraphicsGraphicUtils *create_OrgMapsforgeCoreGraphicsGraphicUtils_init();

@implementation OrgMapsforgeCoreGraphicsGraphicUtils

+ (jint)getAlphaWithInt:(jint)color {
  return OrgMapsforgeCoreGraphicsGraphicUtils_getAlphaWithInt_(color);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMapsforgeCoreGraphicsGraphicUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getAlphaWithInt:);
  methods[1].selector = @selector(init);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getAlpha", "I" };
  static const J2ObjcClassInfo _OrgMapsforgeCoreGraphicsGraphicUtils = { "GraphicUtils", "org.mapsforge.core.graphics", ptrTable, methods, NULL, 7, 0x11, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgMapsforgeCoreGraphicsGraphicUtils;
}

@end

jint OrgMapsforgeCoreGraphicsGraphicUtils_getAlphaWithInt_(jint color) {
  OrgMapsforgeCoreGraphicsGraphicUtils_initialize();
  return (JreRShift32(color, 24)) & (jint) 0xff;
}

void OrgMapsforgeCoreGraphicsGraphicUtils_init(OrgMapsforgeCoreGraphicsGraphicUtils *self) {
  NSObject_init(self);
}

OrgMapsforgeCoreGraphicsGraphicUtils *new_OrgMapsforgeCoreGraphicsGraphicUtils_init() {
  J2OBJC_NEW_IMPL(OrgMapsforgeCoreGraphicsGraphicUtils, init)
}

OrgMapsforgeCoreGraphicsGraphicUtils *create_OrgMapsforgeCoreGraphicsGraphicUtils_init() {
  J2OBJC_CREATE_IMPL(OrgMapsforgeCoreGraphicsGraphicUtils, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMapsforgeCoreGraphicsGraphicUtils)
