//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/core/graphics/Position.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "org/mapsforge/core/graphics/Position.h"

__attribute__((unused)) static void OrgMapsforgeCoreGraphicsPosition_initWithNSString_withInt_(OrgMapsforgeCoreGraphicsPosition *self, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(OrgMapsforgeCoreGraphicsPosition)

OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_values_[10];

@implementation OrgMapsforgeCoreGraphicsPosition

+ (OrgMapsforgeCoreGraphicsPosition *)fromStringWithNSString:(NSString *)value {
  return OrgMapsforgeCoreGraphicsPosition_fromStringWithNSString_(value);
}

+ (IOSObjectArray *)values {
  return OrgMapsforgeCoreGraphicsPosition_values();
}

+ (OrgMapsforgeCoreGraphicsPosition *)valueOfWithNSString:(NSString *)name {
  return OrgMapsforgeCoreGraphicsPosition_valueOfWithNSString_(name);
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgMapsforgeCoreGraphicsPosition;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "[LOrgMapsforgeCoreGraphicsPosition;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgMapsforgeCoreGraphicsPosition;", 0x9, 2, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(fromStringWithNSString:);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "AUTO", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "CENTER", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "BELOW", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "BELOW_LEFT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "BELOW_RIGHT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "ABOVE", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
    { "ABOVE_LEFT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 9, -1, -1 },
    { "ABOVE_RIGHT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 10, -1, -1 },
    { "LEFT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 11, -1, -1 },
    { "RIGHT", "LOrgMapsforgeCoreGraphicsPosition;", .constantValue.asLong = 0, 0x4019, -1, 12, -1, -1 },
  };
  static const void *ptrTable[] = { "fromString", "LNSString;", "valueOf", &JreEnum(OrgMapsforgeCoreGraphicsPosition, AUTO), &JreEnum(OrgMapsforgeCoreGraphicsPosition, CENTER), &JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW), &JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW_LEFT), &JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW_RIGHT), &JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE), &JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE_LEFT), &JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE_RIGHT), &JreEnum(OrgMapsforgeCoreGraphicsPosition, LEFT), &JreEnum(OrgMapsforgeCoreGraphicsPosition, RIGHT), "Ljava/lang/Enum<Lorg/mapsforge/core/graphics/Position;>;" };
  static const J2ObjcClassInfo _OrgMapsforgeCoreGraphicsPosition = { "Position", "org.mapsforge.core.graphics", ptrTable, methods, fields, 7, 0x4011, 3, 10, -1, -1, -1, 13, -1 };
  return &_OrgMapsforgeCoreGraphicsPosition;
}

+ (void)initialize {
  if (self == [OrgMapsforgeCoreGraphicsPosition class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 10 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    id names[] = {
      @"AUTO", @"CENTER", @"BELOW", @"BELOW_LEFT", @"BELOW_RIGHT", @"ABOVE", @"ABOVE_LEFT", @"ABOVE_RIGHT", @"LEFT", @"RIGHT",
    };
    for (jint i = 0; i < 10; i++) {
      (OrgMapsforgeCoreGraphicsPosition_values_[i] = e = objc_constructInstance(self, (void *)ptr), ptr += objSize);
      OrgMapsforgeCoreGraphicsPosition_initWithNSString_withInt_(e, names[i], i);
    }
    J2OBJC_SET_INITIALIZED(OrgMapsforgeCoreGraphicsPosition)
  }
}

@end

void OrgMapsforgeCoreGraphicsPosition_initWithNSString_withInt_(OrgMapsforgeCoreGraphicsPosition *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromStringWithNSString_(NSString *value) {
  OrgMapsforgeCoreGraphicsPosition_initialize();
  if ([@"auto" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW);
  }
  else if ([(@"center") isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, CENTER);
  }
  else if ([(@"below") isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW);
  }
  else if ([(@"below_left") isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW_LEFT);
  }
  else if ([(@"below_right") isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, BELOW_RIGHT);
  }
  else if ([@"above" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE);
  }
  else if ([@"above_left" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE_LEFT);
  }
  else if ([@"above_right" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, ABOVE_RIGHT);
  }
  else if ([@"left" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, LEFT);
  }
  else if ([@"right" isEqual:value]) {
    return JreEnum(OrgMapsforgeCoreGraphicsPosition, RIGHT);
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$$", @"Invalid value for Position: ", value));
}

IOSObjectArray *OrgMapsforgeCoreGraphicsPosition_values() {
  OrgMapsforgeCoreGraphicsPosition_initialize();
  return [IOSObjectArray arrayWithObjects:OrgMapsforgeCoreGraphicsPosition_values_ count:10 type:OrgMapsforgeCoreGraphicsPosition_class_()];
}

OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_valueOfWithNSString_(NSString *name) {
  OrgMapsforgeCoreGraphicsPosition_initialize();
  for (int i = 0; i < 10; i++) {
    OrgMapsforgeCoreGraphicsPosition *e = OrgMapsforgeCoreGraphicsPosition_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

OrgMapsforgeCoreGraphicsPosition *OrgMapsforgeCoreGraphicsPosition_fromOrdinal(NSUInteger ordinal) {
  OrgMapsforgeCoreGraphicsPosition_initialize();
  if (ordinal >= 10) {
    return nil;
  }
  return OrgMapsforgeCoreGraphicsPosition_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMapsforgeCoreGraphicsPosition)
