//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/mapsforge/map/rendertheme/XmlRenderTheme.java
//

#include "J2ObjC_source.h"
#include "org/mapsforge/map/rendertheme/XmlRenderTheme.h"

@interface OrgMapsforgeMapRenderthemeXmlRenderTheme : NSObject

@end

@implementation OrgMapsforgeMapRenderthemeXmlRenderTheme

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgMapsforgeMapRenderthemeXmlRenderThemeMenuCallback;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaIoInputStream;", 0x401, -1, -1, 0, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getMenuCallback);
  methods[1].selector = @selector(getRelativePathPrefix);
  methods[2].selector = @selector(getRenderThemeAsStream);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaIoFileNotFoundException;" };
  static const J2ObjcClassInfo _OrgMapsforgeMapRenderthemeXmlRenderTheme = { "XmlRenderTheme", "org.mapsforge.map.rendertheme", ptrTable, methods, NULL, 7, 0x609, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMapsforgeMapRenderthemeXmlRenderTheme;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgMapsforgeMapRenderthemeXmlRenderTheme)
