//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/kxml2/wap/WbxmlParser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgKxml2WapWbxmlParser")
#ifdef RESTRICT_OrgKxml2WapWbxmlParser
#define INCLUDE_ALL_OrgKxml2WapWbxmlParser 0
#else
#define INCLUDE_ALL_OrgKxml2WapWbxmlParser 1
#endif
#undef RESTRICT_OrgKxml2WapWbxmlParser

#if !defined (OrgKxml2WapWbxmlParser_) && (INCLUDE_ALL_OrgKxml2WapWbxmlParser || defined(INCLUDE_OrgKxml2WapWbxmlParser))
#define OrgKxml2WapWbxmlParser_

#define RESTRICT_OrgXmlpullV1XmlPullParser 1
#define INCLUDE_OrgXmlpullV1XmlPullParser 1
#include "org/xmlpull/v1/XmlPullParser.h"

@class IOSCharArray;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoReader;

@interface OrgKxml2WapWbxmlParser : NSObject < OrgXmlpullV1XmlPullParser >

#pragma mark Public

- (instancetype)init;

- (void)defineEntityReplacementTextWithNSString:(NSString *)entity
                                   withNSString:(NSString *)value;

- (jint)getAttributeCount;

- (NSString *)getAttributeNameWithInt:(jint)index;

- (NSString *)getAttributeNamespaceWithInt:(jint)index;

- (NSString *)getAttributePrefixWithInt:(jint)index;

- (NSString *)getAttributeTypeWithInt:(jint)index;

- (NSString *)getAttributeValueWithInt:(jint)index;

- (NSString *)getAttributeValueWithNSString:(NSString *)namespace_
                               withNSString:(NSString *)name;

- (jint)getColumnNumber;

- (jint)getDepth;

- (jint)getEventType;

- (jboolean)getFeatureWithNSString:(NSString *)feature;

- (NSString *)getInputEncoding;

- (jint)getLineNumber;

- (NSString *)getName;

- (NSString *)getNamespace;

- (NSString *)getNamespaceWithNSString:(NSString *)prefix;

- (jint)getNamespaceCountWithInt:(jint)depth;

- (NSString *)getNamespacePrefixWithInt:(jint)pos;

- (NSString *)getNamespaceUriWithInt:(jint)pos;

- (NSString *)getPositionDescription;

- (NSString *)getPrefix;

- (id)getPropertyWithNSString:(NSString *)property;

- (NSString *)getText;

- (IOSCharArray *)getTextCharactersWithIntArray:(IOSIntArray *)poslen;

- (jint)getWapCode;

- (id)getWapExtensionData;

- (jboolean)isAttributeDefaultWithInt:(jint)index;

- (jboolean)isEmptyElementTag;

- (jboolean)isWhitespace;

- (jint)next;

- (jint)nextTag;

- (NSString *)nextText;

- (jint)nextToken;

- (id)parseWapExtensionWithInt:(jint)id_;

- (void)readAttr;

- (void)requireWithInt:(jint)type
          withNSString:(NSString *)namespace_
          withNSString:(NSString *)name;

- (void)setAttrStartTableWithInt:(jint)page
               withNSStringArray:(IOSObjectArray *)table;

- (void)setAttrValueTableWithInt:(jint)page
               withNSStringArray:(IOSObjectArray *)table;

- (void)setFeatureWithNSString:(NSString *)feature
                   withBoolean:(jboolean)value;

- (void)setInputWithJavaIoInputStream:(JavaIoInputStream *)inArg
                         withNSString:(NSString *)enc;

- (void)setInputWithJavaIoReader:(JavaIoReader *)reader;

- (void)setPropertyWithNSString:(NSString *)property
                         withId:(id)value;

- (void)setTagTableWithInt:(jint)page
         withNSStringArray:(IOSObjectArray *)table;

#pragma mark Protected

- (NSString *)resolveWapExtensionWithInt:(jint)id_
                                  withId:(id)data;

#pragma mark Package-Private

- (void)parseElementWithInt:(jint)id_;

- (jint)readByte;

- (jint)readInt;

- (NSString *)readStrI;

- (NSString *)readStrT;

- (NSString *)resolveIdWithNSStringArray:(IOSObjectArray *)tab
                                 withInt:(jint)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgKxml2WapWbxmlParser)

inline NSString *OrgKxml2WapWbxmlParser_get_HEX_DIGITS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgKxml2WapWbxmlParser_HEX_DIGITS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgKxml2WapWbxmlParser, HEX_DIGITS, NSString *)

inline jint OrgKxml2WapWbxmlParser_get_WAP_EXTENSION();
#define OrgKxml2WapWbxmlParser_WAP_EXTENSION 64
J2OBJC_STATIC_FIELD_CONSTANT(OrgKxml2WapWbxmlParser, WAP_EXTENSION, jint)

FOUNDATION_EXPORT void OrgKxml2WapWbxmlParser_init(OrgKxml2WapWbxmlParser *self);

FOUNDATION_EXPORT OrgKxml2WapWbxmlParser *new_OrgKxml2WapWbxmlParser_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgKxml2WapWbxmlParser *create_OrgKxml2WapWbxmlParser_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgKxml2WapWbxmlParser)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgKxml2WapWbxmlParser")
